version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: bajerlukascz_cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiM2NjZGM4YmUwMzMzOGJlNWJjYjM1ZWIxYzc2OGExYzQiLCJ0IjoiOGM4YTcxMGItOWViNy00YzI3LWE0NDItYjhmZWQ5NDUwY2MwIiwicyI6IllUQXpPV05qT0RjdE5EQmpaUzAwWXpkbExXRXlNVEF0WVdObVlUUmpNVE5oWW1JdyJ9
    networks:
      - bajerlukascz_network

networks:
  bajerlukascz_network:
    name: bajerlukascz_network
    driver: bridge